# pages:
#   stage: deploy
#   image: node:16.14.0-alpine
#   script:
#     - git config user.email "moberholzer.mmt-b2020@fh-salzburg.ac.at"
#     - git config user.name "ci-bot"
#     - git remote add dokku ssh://dokku@projects.multimediatechnology.at:5412/cr2023
#     - dokku ps:rebuild
#   only:
#     - main
image: dokku/ci-docker-image

stages:
  - deploy

variables:
  GIT_DEPTH: 0

deploy:
  stage: deploy
  only:
    - master
  environment:
    name: production
    url: https://cr2023.projects.multimediatechnology.at/
  variables:
    GIT_REMOTE_URL: ssh://dokku@projects.multimediatechnology.at:5412/cr2023
  script: 
    - -v="$COMMAND:ps_rebuild" dokku-deploy
  after_script: 
    - dokku-unlock
# stages:
#   - deploy

# variables:
#   APP_NAME: cr2023

# deploy:
#   image: ilyasemenov/gitlab-ci-git-push
#   stage: deploy
#   environment:
#     name: production
#     url: https://cr2023.projects.multimediatechnology.at/
#   only:
#     - master
#   script:
#     - git-push ssh://dokku@projects.multimediatechnology.at:5412/cr2023
# image: alpine:latest

# stages:
#   - deploy

# deploy:
#   image: ilyasemenov/gitlab-ci-git-push
#   stage: deploy
#   only:
#     - main
#   script:
#     - git-push ssh://dokku@projects.multimediatechnology.at:5412/cr2023 main:master
# pages:
#   stage: deploy
#   image: node:16.14.0-alpine
#   script:
#     - git config user.email "moberholzer.mmt-b2020@fh-salzburg.ac.at"
#     - git config user.name "ci-bot"
#     - git remote add dokku https://projects.multimediatechnology.at:5412/cr2023
#     - git add .
#     - git commit -m "push back from pipeline"
#     - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
#   only:
#     - main
# pages:
#   stage: deploy
#   image: node:16.14.0-alpine
#   script:
#     - npm install
#     - npm run build
#     - npm run export
#     - rm -rf public/*
#     - mv out/* public
#   artifacts:
#     paths:
#       - public
#   cache:
#     paths:
#       - node_modules
#       - .next/cache/
#   only:
#     - main
