image: alpine:latest

pages:
  stage: deploy
  script:
    - npm install
    - npm build
    - npm export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
      - .next/cache/
  only:
    - main
