image: alpine:latest

pages:
  stage: deploy
  image: node:16.14.0-alpine
  script:
    - npm install
    - npm run build
    - npm run export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
      - .next/cache/
  only:
    - main
