image: alpine:latest

pages:
  stage: deploy
  script:
    - pnpm install
    - pnpm build
    - pnpm export
    - rm -rf public/*
    - mv out/* public
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
      - .next/cache/
  only:
    - main
